### ISSUE TITLE
Error: end of central directory record signature not found

### ISSUE THREAD

**Issue by alouanemed** [vzsg/auto-adhoc-distribution-site#1]
First build and I got this error:

```
Build succeeded
2019-06-25T10:32:30.776095+00:00 heroku[web.1]: Starting process with command `node app.js`
2019-06-25T10:32:33.250684+00:00 heroku[web.1]: State changed from starting to crashed
2019-06-25T10:32:33.258520+00:00 heroku[web.1]: State changed from crashed to starting
2019-06-25T10:32:33.231239+00:00 heroku[web.1]: Process exited with status 0
2019-06-25T10:32:32.979191+00:00 app[web.1]: Searching for packages...
2019-06-25T10:32:32.990342+00:00 app[web.1]: Parsing packages...
2019-06-25T10:32:32.999518+00:00 app[web.1]: Error: end of central directory record signature not found
2019-06-25T10:32:32.999522+00:00 app[web.1]: at /app/node_modules/yauzl/index.js:187:14
2019-06-25T10:32:32.999524+00:00 app[web.1]: at Immediate.<anonymous> (/app/node_modules/yauzl/index.js:624:38)

```

**Comment by vzsg** [comment]
The error suggests that something is wrong with your IPA, as if it wasn't a valid zip archive. That would explain the failed installations from the old site too.

**Comment by vzsg** [comment]
Or, I messed up and that .gitkeep file kills the server which I added at the last moment before commit. BRB.

**Comment by vzsg** [comment]
Yeah, that was it, sorry about that.
It should work correctly now.

**Comment by alouanemed** [comment]
Yeah,  that was my observation, I removed the gikeep file and it solved.
